project_id = "bkqzrfuyjugegxcqxwuo"

[functions.get-weather]
verify_jwt = false

[functions.generate-recommendation] 
verify_jwt = false

[functions.ml-prediction]
verify_jwt = false

[functions.getFertilizerRecommendation]
verify_jwt = false

[functions.validate-crop-image]
verify_jwt = false

[functions.extract-soil-health-card]
verify_jwt = false